### ISSUE TITLE
"Progress over processes" artifact

### ISSUE THREAD

**Issue by bearcanrun** [sandrina-p/portfolio_v3#2]
Maybe you were setting up a pun, but currently word "processes" falls behind the supporting content box. On a Mac in Chrome. 

![Screen Shot 2020-02-27 at 11 43 30 AM](https://user-images.githubusercontent.com/361344/75481002-2cfc9900-5957-11ea-9b46-2d3679aaa8c8.png)

**Comment by sandrina-p** [comment]
Hi @bearcanrun

Yes, this was intentional! 😅
It was a funny trick I created to play with words and using design to emphasise to the meaning behind it.
